# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Fixs
      labels:
        - fix
    - title: Feats
      labels:
        - feat
    - title: Chores
      labels:
        - enhancement
        - chore
        - deploy
    - title: Other Changes
      labels:
        - "*"
